Add type declarations
sonata-project/SonataDoctrineMongoDBAdminBundle pull request #537
Opened 2021-02-22 00:06 UTC by franmomu

This PR resolves `NEXT_MAJOR` comments and adds missing type declarations.

2021-02-22 07:49 UTC, VincentLanglet commented on src/Exporter/DataSource.php
>              throw new \LogicException(sprintf('Argument 1 MUST be an instance of "%s"', ProxyQuery::class));
You have to update the exception too

2021-02-22 07:49 UTC, VincentLanglet commented on src/Model/ModelManager.php
> -     * @phpstan-return array{
Why removing this ?

2021-02-22 08:12 UTC, franmomu commented on src/Model/ModelManager.php
> -     * @phpstan-return array{
my bad, fixed.

2021-02-22 08:15 UTC, VincentLanglet submitted a review, later dismissed

2021-02-22 19:10 UTC, phansys requested changes

2021-02-22 19:10 UTC, phansys commented on src/Filter/StringFilter.php
> +        if (!\array_key_exists('value', $data) || null === $data['value']) {
```suggestion
        if (null === $data['value'] ?? null) {
```

2021-02-23 00:05 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-02-23 01:52 UTC, VincentLanglet approved these changes

2021-02-23 18:09 UTC, VincentLanglet submitted a review, later dismissed

2021-03-13 11:17 UTC, dmaicher approved these changes

2021-03-13 11:19 UTC, VincentLanglet commented
Can you take a new look @phansys ?

2021-03-13 13:29 UTC, phansys requested changes

2021-03-13 13:29 UTC, phansys commented on src/Filter/AbstractDateFilter.php
> +        return $choices[$type];
Maybe we should check that the passed offset is defined and throw an exception otherwise.

2021-03-13 13:29 UTC, phansys commented on src/Model/ModelManager.php
>              throw new \RuntimeException(sprintf('No document manager defined for class %s', $class));
```suggestion
            throw new \TypeError(sprintf(
                'Document manager for class "%s" must be of type "%s".',
                $class,
                DocumentManager::class
            ));
```

2021-03-13 13:29 UTC, phansys commented on tests/App/AppKernel.php
> +    public function registerBundles(): array
```suggestion
    public function registerBundles(): iterable
```

2021-03-18 09:27 UTC, phansys approved these changes

2021-03-18 09:27 UTC, phansys commented on src/Filter/AbstractDateFilter.php
> +                implode(', ', array_keys($choices))
```suggestion
                implode('", "', array_keys($choices))
```

2021-03-18 09:27 UTC, phansys commented on src/Filter/AbstractDateFilter.php
> +                'Type "%d" not valid, you should use one of these: "%s"',
```suggestion
                'Type "%d" is not valid, you MUST use one of the supported types: "%s".',
```

2021-03-30 17:27 UTC, closed without merging